all:
  children:
    guacamole:
      hosts:
        guacamole-dev:
          ansible_host: 52.201.46.244
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/roczyno/.ssh/cylynk-lab-keypair
          environment: dev
          project_name: cyberlab
          domain_name: ""
          admin_email: "dev-admin@yourdomain.com"
          enable_lets_encrypt: false
          guacamole_db_password: "ChangeMe!SetARealPassword123"
